trigger:
  branches:
    include:
      - main
      - develop

variables:
  imageName: 'smartparking'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: DockerBuild
        steps:
          - task: Checkout@1  # Faz o checkout do código do repositório

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              Dockerfile: './Dockerfile'  # Caminho correto do Dockerfile na raiz
              buildContext: $(Build.SourcesDirectory)  # Define o diretório de contexto da build
              repository: 'smartparking'  # Usando o nome fixo para a imagem
              tags: |
                smartparking:$(Build.SourceBranchName)-$(Build.BuildId)  # Tag com o nome fixo da imagem

  - stage: Deploy
    displayName: "Deploy Application"
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "Iniciando deploy da aplicação..."
              docker run -d -p 8080:8080 smartparking:$(Build.SourceBranchName)-$(Build.BuildId)
            displayName: "Rodar container"
