trigger:
  branches:
    include:
      - main
      - develop

variables:
  imageName: 'smartparking'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: DockerBuild
        displayName: "Docker Build Job"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              dockerfile: 'Dockerfile'  # Nome do Dockerfile (na raiz do projeto)
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(imageName):$(Build.SourceBranchName)-$(Build.BuildId)

  - stage: Deploy
    displayName: "Deploy Application"
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: "Run Container"
        steps:
          - script: |
              echo "Iniciando deploy da aplicação localmente..."
              docker run -d -p 8080:8080 $(imageName):$(Build.SourceBranchName)-$(Build.BuildId)
            displayName: "Rodar container"
