trigger:
  branches:
    include:
      - main
      - develop

variables:
  imageName: 'smartparking'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: DockerBuild
        steps:
          - task: Checkout@1  # Faz o checkout do código do repositório

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              Dockerfile: '**/Dockerfile'
              repository: $(imageName)
              tags: |
                $(Build.SourceBranchName)-$(Build.BuildId)

  - stage: Deploy
    displayName: "Deploy Application"
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "Iniciando deploy da aplicação..."
              docker run -d -p 8080:8080 $(imageName):$(Build.SourceBranchName)-$(Build.BuildId)
            displayName: "Rodar container"
