version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartparking-db
    restart: always
    environment:
      POSTGRES_DB: smartparkingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - smartnet

  app:
    build: .
    container_name: smartparking-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartparkingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - postgres
    networks:
      - smartnet

networks:
  smartnet:

volumes:
  pgdata:
