version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartparking-db
    restart: always
    environment:
      POSTGRES_DB: smartparkingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - smartnet

volumes:
  pgdata:

networks:
  smartnet:
    driver: bridge
